// File generated by the FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Platform Projects Generated by the FlutterFire CLI.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForWebDevelopment123456789',
    appId: '1:578482275296:web:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '578482275296',
    projectId: 'mcs-medical-clinic-management',
    authDomain: 'mcs-medical-clinic-management.firebaseapp.com',
    storageBucket: 'mcs-medical-clinic-management.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForAndroidDevelopment123456789',
    appId: '1:578482275296:android:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '578482275296',
    projectId: 'mcs-medical-clinic-management',
    storageBucket: 'mcs-medical-clinic-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForIOSDevelopment123456789',
    appId: '1:578482275296:ios:b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '578482275296',
    projectId: 'mcs-medical-clinic-management',
    storageBucket: 'mcs-medical-clinic-management.firebasestorage.app',
    iosBundleId: 'com.example.mcs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForMacOSDevelopment123456789',
    appId: '1:578482275296:macos:c3d4e5f6g7h8i9j0k1l2',
    messagingSenderId: '578482275296',
    projectId: 'mcs-medical-clinic-management',
    storageBucket: 'mcs-medical-clinic-management.firebasestorage.app',
    iosBundleId: 'com.example.mcs',
  );
}
